### ISSUE TITLE
Does not support node 0.10

### ISSUE THREAD

**Issue by mmeroberts** [jtblin/syncho#2]
Is there a reason that synchro does not support versions of node greater than 0.8?

**Comment by jtblin** [comment]
Not sure where you've seen that.

I use `syncho` in several projects in production with `0.10.x`. `syncho` supports all node version greater than `0.5.2` same as [Fibers](https://github.com/laverdet/node-fibers) module that it depends on as you can see in [package.json](https://github.com/jtblin/syncho/blob/master/package.json):

```
"engines": {
    "node": ">=0.5.2"
  }
```

Recently I had to lock `Fibers` to `0.1.2` as `0.1.3` was broken. As this is fixed now, I am going to change the dependency to require `0.1.5` which include support for node `0.11.x`.
